ame: Use GCloud Action

description: |
  This GitHub Action sets up the Google Cloud SDK, prints authentication information,
  and calls a shell script.

on:
  push:
    branches:
      - main

jobs:
  use-gcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Use gcloud CLI
      run: |
        gcloud auth list
      shell: bash
