name: Test pipeline failure 

on:
  push:
    branches:
      - main

jobs:
  use-gcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Push API Documentation
      run: |
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Test commit" || echo "Nothing to commit"
          git push || echo "Nothing to push"
