name: Second workflow

on:
  push:
    branches-ignore:
      - main
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Print second workflow
        run: |
          echo ${{ github.event.number }} 
          echo ${{ github.event.workflow_run.head_branch }}
